spring:
  mvc:
    favicon:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  jmx:
    default-domain: shopper
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      client:
        registration:
          google:
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

logging:
  level:
    org.springframework.cache: ERROR
    org.apache.http: ERROR
    org.springframework.web.client.RestTemplate: ERROR
    org.apache.commons.beanutils: ERROR
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
    org.springframework.security: ERROR
    org.springframework.web.filter.CommonsRequestLoggingFilter: ERROR
    org.springframework.web: ERROR
    org.springframework.web.socket.config.WebSocketMessageBrokerStats: ERROR
app:
  name: Shopper

###############################################################################################
# Below more properties which should be set via external file , and provided via              #
# - context param : shopper.properties.path                                                   #
# - System property : properties.location                                                     #
###############################################################################################

#app:
#  category:
#    order: FRUIT_VEGETABLES,BAKERY,BREAKFAST,BABY,CANNED,CAR,CLOTHES,COFFEE_TEA,COSMETICS,DIARY,DIET,ELECTRONICAL,FISH,FROZEN,GRAINS_FLOURS,PASTA,HOME_KITCHEN,HOME_BAKING,CLEANING,MEAT,NEWSPAPERS,OFFICE_SUPPLIES,OILS,HYGIENE,PET,PHARMACY,PRESERVES,READY_MEALS,SNACKS,SPICES,BEVERAGES,ALCOHOL,GARDEN,BUILDING,TOYS,OTHER
#  newsletter:
#    schedule: 0 0 20-22 * * MON
#security:
#  oauth2:
#    client:
#      client-id: shopper
#      client-secret: 205a973f43d75da1524f133d14456ba1
#      scope: read,write
#      auto-approve-scopes: '.*'
#    resource:
#      userInfoUri: "*"
#    client:
#      client-id: shopper
#      client-secret: SECRET
#      scope: read,write
#      auto-approve-scopes: '.*'
#      registration:
#        google:
#          clientId: CLIENT_ID
#          clientSecret: SECRET
#          redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
#          scope:
#            - email
#            - profile
#        facebook:
#          clientId: CLIENT_ID
#          clientSecret: SECRET
#          redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
#          scope:
#            - email
#            - public_profile
#      provider:
#        facebook:
#          authorizationUri: https://www.facebook.com/v6.0/dialog/oauth
#          tokenUri: https://graph.facebook.com/v6.0/oauth/access_token
#          userInfoUri: https://graph.facebook.com/v6.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
#spring:
#  mail:
#    host: localhost
#    port: 25
#    protocol: smtp
#    from: shopper@q-programming.pl
#    username: us
#    password: ps
#    default-encoding: UTF-8
#  datasource:
#    #    url: jdbc:h2:./db/shopperH2databaseFile;AUTO_SERVER=TRUE
#    #    username: sa
#    #    password:
#    url: jdbc:postgresql://localhost:5432/shopper
#    username: shopper
#    password: cZmYpQWeJXSaWEUHSp3V
#jwt:
#  header: Authorization
#  expires_in: 604800 # week
#  secret: f3d5b3b563588950d76197756b73a022822c347bd7da934fb171cf6458e94b3e
#  cookie: COOKIE-AUTH-TOKEN
#  xsrf: XSRF-TOKEN
#  jsessionid: JSESSIONID
#  user_cookie: c_user
