image: khobar/docker-jdk-8-maven-node-ng
stages:
  - build_application
  - test_application

# This stage builds your application
build_application:
  stage: build_application
  script:
    - mvn clean install -DskipTests=false
test_application:
  stage: test_application
  script:
    - mvn surefire:test