export enum Category {
    ALCOHOL = "ALCOHOL", BABY = "BABY", BAKERY = "BAKERY", BEVERAGES = "BEVERAGES", CANNED = "CANNED", CAR = "CAR", CLOTHES = "CLOTHES",
    COFFEE_TEA = "COFFEE_TEA", COSMETICS = "COSMETICS", DIARY = "DIARY", DIET = "DIET", ELECTRONICAL = "ELECTRONICAL", FISH = "FISH",
    FROZEN = "FROZEN", GRAINS_FLOURS = "GRAINS_FLOURS", HOME_KITCHEN = "HOME_KITCHEN", HOME_BAKING = "HOME_BAKING", CLEANING = "CLEANING",
    MEAT = "MEAT", NEWSPAPERS = "NEWSPAPERS", OFFICE_SUPPLIES = "OFFICE_SUPPLIES", OILS = "OILS", HYGIENE = "HYGIENE", PET = "PET",
    PHARMACY = "PHARMACY", PRESERVES = "PRESERVES", FRUIT_VEGETABLES = "FRUIT_VEGETABLES", READY_MEALS = "READY_MEALS", SNACKS = "SNACKS",
    SPICES = "SPICES", GARDEN = "GARDEN", OTHER = "OTHER", BUILDING = "BUILDING", BREAKFAST = "BREAKFAST", TOYS = "TOYS", PASTA = "PASTA"
}
