version: 2
jobs:
  build:
    docker:
      - image: khobar/docker-jdk-8-maven-node-ng
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-
      - run:
          name: Build application
          command: mvn clean install -DskipTests=true
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
  test:
    docker:
      - image: khobar/docker-jdk-8-maven-node-ng
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-
      - run:
          name: Test
          command: mvn integration-test
      - store_artifacts:
          path: /root/repo/shopper-app/target/shopper.war
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build