package pl.qprogramming.shopper.watch.model;

public enum Category {
    ALCOHOL, BABY, BAKERY, BEVERAGES, CANNED, CAR, CLOTHES, COFFEE_TEA, COSMETICS, DIARY, DIET, ELECTRONICAL, FISH, FROZEN,
    GRAINS_FLOURS, HOME_KITCHEN, HOME_BAKING, CLEANING, MEAT, NEWSPAPERS, OFFICE_SUPPLIES, OILS, OTHER, HYGIENE, PET,
    PHARMACY, PRESERVES, FRUIT_VEGETABLES, READY_MEALS, SNACKS, SPICES, GARDEN, BUILDING, BREAKFAST, TOYS, PASTA
}
