app:
  default:
    lang: en
  category:
    order: FRUIT_VEGETABLES,BAKERY,BREAKFAST,BABY,CANNED,CAR,CLOTHES,COFFEE_TEA,COSMETICS,DIARY,DIET,ELECTRONICAL,FISH,FROZEN,GRAINS_FLOURS,PASTA,HOME_KITCHEN,HOME_BAKING,CLEANING,MEAT,NEWSPAPERS,OFFICE_SUPPLIES,OILS,HYGIENE,PET,PHARMACY,PRESERVES,READY_MEALS,SNACKS,SPICES,BEVERAGES,ALCOHOL,GARDEN,BUILDING,TOYS,OTHER
  newsletter:
    schedule: 0 0 2-3 * * MON

spring:
  mail:
    host: localhost
    port: 25
    protocol: smtp
    from: shopper@q-programming.pl
    username: us
    password: ps
    default-encoding: UTF-8
  datasource:
    url: jdbc:postgresql://192.168.1.50:5432/shopper
    username: postgres
    password: password
  security:
    oauth2:
      resource:
        userInfoUri: "*"
      client:
        registration:
          google:
            clientId: CLIENT_ID
            clientSecret: CLIENT_SECRET
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: CLIENT_ID
            clientSecret: CLIENT_SECRET
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v6.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v6.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v6.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

jwt:
  header: Authorization
  expires_in: 604800 # week
  secret: a3d5b3b563588950d76197756b73a022822c347bd7da934fb171cf6458e94b3e
  cookie: SHOPPER-COOKIE-AUTH-TOKEN
  xsrf: XSRF-TOKEN
  jsessionid: JSESSIONID
  user_cookie: c_user
