package com.qprogramming.shopper.app.items.category;

/**
 * Created by Jakub Romaniszyn on 2018-08-14
 */
public enum Category {
    ALCOHOL, BABY, BAKERY, BEVERAGES, CANNED, CAR, CLOTHES, COFFEE_TEA, COSMETICS, DIARY, DIET, ELECTRONICAL, FISH, FROZEN,
    GRAINS_PASTA, HOME_KITCHEN, HOME_BAKING, CLEANING, MEAT, NEWSPAPERS, OFFICE_SUPPLIES, OILS, OTHER, HYGIENE, PET,
    PHARMACY, PRESERVES, FRUIT_VEGETABLES, READY_MEALS, SNACKS, SPICES, GARDEN, BUILDING, BREAKFAST, TOYS
}
