name: Build

on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: Cache setup
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
      with:
        node-version: 12    

    - name: Install Angular-CLI
      run: npm install --unsafe-perm -g @angular/cli        
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.1.0
      with:
        java-version: 1.8
    
    - name: Build with Maven
      run: mvn clean package

    - name: Store artefact
      uses: actions/upload-artifact@v1
      with:
        name: shopper.war
        path: shopper-app/target/shopper.war
      
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}